### ISSUE TITLE
serial.read_character cannot decode response to serial.send('STATUS?')

### ISSUE THREAD

**Issue by PicoPET** [PicoPET/py-korad-serial#1]
Tested on Korad KA-3005P (model string `KORADKA3005PV2.0`) using commit 87fee82ec5ce564b0c4ac2b8d08cb52b945b9b5a with both Python 2.7.15 and 3.6.7: the first byte of response could not be decoded:

```
>>> device = KoradSerial('/dev/ttyACM0')
>>> print(device.model)
KORADKA3005PV2.0
>>> device.serial.send('STATUS?')
>>> c = device.serial.read_character()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "koradserial.py", line 240, in read_character
    c = self.port.read(1).decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb1 in position 0: ordinal not in range(128)
>>> 
```

Same result with the `utf-8` codec.

Apparently on this device model all 8 bits of status are being used, with
* bit 7 representing overvoltage protection status
* bit 5 representing overcurrent protection status (instead of `Lock` status)

**Comment by PicoPET** [comment]
The use of all 8 bits means that the character should be read and processed as a byte, rather than being decoded to string before analysis.

**Comment by PicoPET** [comment]
Reading fixed in commit f1be25f.

**Comment by PicoPET** [comment]
The detailed format of the status (depending on HW/FW version etc.) will be handled as a separate issue #2.
